# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cosipy.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.BInput = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BInput.setObjectName("BInput")
        self.gridLayout.addWidget(self.BInput, 0, 3, 1, 1)
        self.TInputFolder = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.TInputFolder.setObjectName("TInputFolder")
        self.gridLayout.addWidget(self.TInputFolder, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.TInputFilename = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.TInputFilename.setObjectName("TInputFilename")
        self.gridLayout.addWidget(self.TInputFilename, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.TOutputFilename = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.TOutputFilename.setObjectName("TOutputFilename")
        self.gridLayout.addWidget(self.TOutputFilename, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.startDate = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 4, 2, 1, 1)
        self.endDate = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.endDate.setDate(QtCore.QDate(2010, 1, 1))
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.gridLayout.addWidget(self.endDate, 5, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 210, 171, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COSIPY"))
        self.label.setText(_translate("MainWindow", "COSIPY Input File Folder Path"))
        self.BInput.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "COSIPY Input File Name"))
        self.label_3.setText(_translate("MainWindow", "Output File Name"))
        self.label_4.setText(_translate("MainWindow", "Start Date"))
        self.label_5.setText(_translate("MainWindow", "End Date"))
        self.startDate.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy hh:mm:ss"))
        self.endDate.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy hh:mm:ss"))
        self.pushButton.setText(_translate("MainWindow", "Run COSIPY"))
